const escape = (value) => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]);
const cash = (value, currency, digits = 2) => value == null ? "Quote required" : new Intl.NumberFormat(currency === "INR" ? "en-IN" : "en-US", {style:"currency", currency, minimumFractionDigits:digits, maximumFractionDigits:digits}).format(Number(value));
export function marketView(data) {
  if (!data) return '<main class="main"><h1>Loading supplier evidence…</h1></main>';
  const r = data.reference, c = data.calculation, offer = r.offers[c.currency];
  const link = (url, label) => `<a class="btn" href="${escape(url)}" target="_blank" rel="noopener noreferrer">${escape(label)} ↗</a>`;
  return `<main id="main" class="market-page"><header class="market-top"><div class="brand"><div class="brand-mark">L<span>↗</span></div><div>LastBuy<small>COMMIT WITH EVIDENCE</small></div></div><a class="btn" href="/">Decision workspace →</a></header>
  <div class="eyebrow">PUBLIC SUPPLIER EVIDENCE · ${escape(r.supplier)}</div><h1>A real part. A real deadline.</h1><p class="subtitle">${escape(r.manufacturer)} ${escape(r.manufacturer_part_number)}<br>${escape(r.description)}</p>
  <div class="market-status"><span class="badge warn">${escape(r.lifecycle)}</span><span>Observed ${escape(new Date(r.observed_at).toLocaleString("en-GB", {timeZone:"UTC"}))} UTC</span><span>Reference refresh due after 24 hours</span></div>
  <div class="metric-grid"><div class="metric"><div class="label">LAST-TIME-BUY DATE</div><div class="value market-date">7 Oct 2026</div><div class="foot">Manufacturer notice ${escape(r.notice_id)}</div></div><div class="metric"><div class="label">OBSERVED DISTRIBUTOR STOCK</div><div class="value">${r.stock_observed.toLocaleString()}<small>units</small></div><div class="foot">Backorders unavailable · stock is not reserved</div></div><div class="metric"><div class="label">FINAL SHIPMENT DATE</div><div class="value market-date">7 Apr 2027</div><div class="foot">NCNR · non-cancelable, non-returnable</div></div></div>
  <div class="workspace"><div class="stack"><section class="panel"><header class="panel-header"><div><h2>Exact published price tiers</h2><p>${escape(offer.market)} · directly observed prices, no FX conversion</p></div></header><div class="table-scroll"><table class="evidence-table"><thead><tr><th>Quantity</th><th>Per unit</th><th>Listed line total</th></tr></thead><tbody>${offer.tiers.map(t=>`<tr><td>${t.quantity}</td><td>${cash(t.unit_price,c.currency,5)}</td><td>${cash(t.extended_price,c.currency)}</td></tr>`).join("")}</tbody></table></div><div class="panel-footer">${link(offer.url, "Open supplier listing")}</div></section>
  <section class="panel"><header class="panel-header"><div><h2>Manufacturer evidence</h2><p>Notice issued 7 January 2026 · affected part verified in the parts table.</p></div></header><div class="panel-body"><p>${escape(r.notice_summary)}</p><div class="actions">${link(r.notice_url, "Read discontinuance notice")}</div><p class="note mono">PDF SHA-256: ${escape(r.notice_sha256)}</p></div></section></div>
  <div class="stack"><section class="panel"><header class="panel-header"><div><h2>Check a planning quantity</h2><p>A catalogue estimate does not create a purchase decision.</p></div></header><div class="panel-body"><form id="market-form"><div class="market-fields"><label for="market-currency">Supplier catalogue<select id="market-currency" name="currency"><option value="INR" ${c.currency === "INR"?"selected":""}>India · INR</option><option value="USD" ${c.currency === "USD"?"selected":""}>United States · USD</option></select></label><label for="market-quantity">Requested units<input id="market-quantity" name="quantity" type="number" min="1" max="1000000" step="1" required value="${c.quantity}"></label></div><button class="btn primary" type="submit">Check quantity & price</button></form><div class="market-estimate"><div class="label">${c.status === "QUOTE_REQUIRED" ? "SUPPLIER CONFIRMATION REQUIRED" : "CATALOGUE SUBTOTAL"}</div><div class="value">${cash(c.subtotal,c.currency)}</div>${c.subtotal ? `<p>${c.quantity.toLocaleString()} × ${cash(c.unit_price,c.currency,5)} · ${c.tier_quantity}+ tier</p>` : ""}</div>${c.reasons.length ? `<div class="callout error">${c.reasons.map(escape).join("<br>")}${c.observed_stock_shortfall ? `<br>Observed stock shortfall: <b>${c.observed_stock_shortfall.toLocaleString()} units</b>.` : ""}</div>` : '<p class="note">Quantity is within observed stock. Reconfirm price and allocation with the supplier before commitment.</p>'}<p class="note">Unit precision is preserved; the line total is rounded once. Taxes, duties, tariffs, delivery and customer discounts are not included. Final payable amount requires a supplier quote or checkout.</p></div></section>
  <section class="panel"><header class="panel-header"><div><h2>A replacement is available to investigate</h2><p>${escape(r.replacement.manufacturer_part_number)}</p></div></header><div class="panel-body"><p>${escape(r.replacement.qualification)}</p><p>Observed replacement stock: <b>${r.replacement.stock_observed.toLocaleString()}</b>. Listed one-unit price: <b>${cash(r.replacement.single_unit_price[c.currency],c.currency,5)}</b>.</p><p class="note">Replacement stock is kept separate. The listed 2,600-unit manufacturer standard package for the DR part is not treated as an established order minimum.</p>${link(r.replacement.url,"Inspect replacement")}</div></section></div></div>
  <footer class="footnote"><span>Public commercial facts with a user-selected planning quantity. No customer inventory, contract, qualification or savings is asserted.</span><span>Reference ${escape(data.reference_sha256.slice(0,12))}</span></footer></main>`;
}
